name: KfK-Butler
description: Ein Hilfsprogramm für die Gilde Kalimdor Fired Kodo
markdown: kramdown
theme: jekyll-theme-tactile
show_downloads: falsw
plugins:
  - jekyll-relative-links
relative_links:
  enabled: true
  collections: true
