name: KfK-Butler
description: Ein Hilfsprogramm für die Gilde Kalimdor Fried Kodo
markdown: kramdown
theme: jekyll-theme-tactile
show_downloads: false
plugins:
  - jekyll-titles-from-headings
  - jekyll-relative-links
titles_from_headings:
  enabled:     true
  strip_title: true
  collections: true
relative_links:
  enabled: true
  collections: true
