name: KfK-Butler
description: Ein Hilfsprogramm für die Gilde Kalimdor Fired Kodo
markdown: kramdown
theme: jekyll-theme-tactile
show_downloads: ["true" or "false" to indicate whether to provide a download URL]
plugins:
  - jekyll-relative-links
relative_links:
  enabled: true
  collections: true
